
title: Having, Doing, and Being
email: dr.kiwi.j
my_word: hakuna matata :-)
about_me: Univ. of Seoul, Computer Science and Philosophy
# baseurl: 
url: https://autumnjazz.github.io
instagram_username: dr.kiwi.j
github_username: autumnjazz
author: Darae Jang

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge


plugins:
  - jekyll-paginate
  # - jekyll-polyglot

exclude:
  - Gemfile
  - Gemfile.lock

# pagination
paginate: 7
paginate_path: "/posts/page/:num" 

# multilang
# languages: ['ja', 'ko', 'en']
# default_lang: 'ko'
# exclude_from_localization: ['javascript', 'images', 'css']
# parallel_localization: false